"""empty message

Revision ID: d79054fb3459
Revises: 1adc4cac514d
Create Date: 2022-05-31 03:07:58.746451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd79054fb3459'
down_revision = '1adc4cac514d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_name', table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_name', 'users', ['name'], unique=False)
    # ### end Alembic commands ###
